### ISSUE TITLE
Create .editorconfig.yml file to standardize the code writing rules

### ISSUE THREAD

**Issue by mykola-digtiar** [TU-ADSP/Blockchain-Logging-Framework#23]

**Comment by PaulsBecks** [comment]
Okay so linting is already implemented with spotless. https://github.com/diffplug/spotless/tree/master/plugin-maven 

This is how all files are linted right now, and I don't think we should change it as it's already consistent now.

**Comment by PaulsBecks** [comment]
You can add it to the jenkins checks `mvn spotless:check` and let the pipeline fail if it doesn't return successfully. 

There are plugins for different IDEs to support spotless as well.

**Comment by PaulsBecks** [comment]
@Neckster @Rohrschacht I thought you might want to comment on this.

**Comment by mykola-digtiar** [comment]
@PaulsBecks Regarding the spotless (already available code linter), this is of course cool that we have spotless in place BUT spotless can only be used feasibly in VSCode because there is a plugin available there. And we don’t want to force other developers (including us) to switch to VSCode just to have a linting tool available in the IDE

I propose that we still switch to .editorconfig as it is supported by most of the popular IDEs (without any plugins), define our rules in the .editorconfig.yml, and either keep old linting rules (which is OK) or rewrite the code to follow our linting rules

There is no spotless plugin available for IntelliJ and there is one for eclipse (which can be broken anytime)
