### ISSUE TITLE
Gather backgorund knowledge

### ISSUE THREAD

**Issue by hb237** [TU-ADSP/Blockchain-Logging-Framework#3]
A short outline of the plans discussed in the first meeting on 12.11.2020:

- Work through the papers proposed by the supervisors: [paper one](https://github.com/ADSP-2020/Ethereum-Logging-Framework/files/5530498/EasyChair-Preprint-1356.pdf), [paper two](https://github.com/ADSP-2020/Ethereum-Logging-Framework/files/5530502/2001.10281.pdf)
- Get familiar with XES
- [Get familiar with process mining](https://www.win.tue.nl/~hverbeek/downloads/preprints/Aalst07b.pdf)  
- Check out the repository, build it
- Setup the development environment
   - Small local test network 
   - Common test network
   - Access to fully functional etherium node
- Ultimate goal: [Repeat results in Hendrik's paper](https://github.com/ADSP-2020/Ethereum-Logging-Framework/files/5530486/Process_Mining_with_ELF_v2.pdf)
- If needed, [check out the SCRUM paper](https://github.com/ADSP-2020/Ethereum-Logging-Framework/files/5530490/schwapub.pdf)

https://www.scruminc.com/scrum-papers/

Read about the GitHub milestones.

**Comment by mykola-digtiar** [comment]
👍
