### ISSUE TITLE
Add keyword KEY_WS into the grammar to explicitly define a web socket connection

### ISSUE THREAD

**Issue by mykola-digtiar** [TU-ADSP/Blockchain-Logging-Framework#42]
This increases the readability of the code. However, if no keyword (KEY_IPC or KEY_WS) is set the default could be a web socket connection.

**Comment by rohrschacht** [comment]
@Neckster @6696 @Knostpe Do you think this is still relevant?

**Comment by mykola-digtiar** [comment]
@Rohrschacht not really I think...
